"""add profile photo and join date to cliente

Revision ID: 01304a9b5081
Revises: e155679ec2eb
Create Date: 2025-12-22 10:44:49.595602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01304a9b5081'
down_revision = 'e155679ec2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
