"""add_tracking_fields

Revision ID: 07e5812abfb7
Revises: 1ff45682dcc2
Create Date: 2025-12-24 03:42:50.012988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e5812abfb7'
down_revision = '1ff45682dcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_rastreio', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transportadora', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('transportadora')
        batch_op.drop_column('codigo_rastreio')

    # ### end Alembic commands ###
