"""add registro juridico antifraude vendas

Revision ID: 13b5a74768fe
Revises: ab25ac52ce91
Create Date: 2026-07-30 21:47:58.391456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b5a74768fe'
down_revision = 'ab25ac52ce91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termos_aceitos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ip_comprador', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('ip_comprador')
        batch_op.drop_column('termos_aceitos')

    # ### end Alembic commands ###
