"""add_dimensoes_frete_to_produto

Revision ID: 1ff45682dcc2
Revises: c156be297dc4
Create Date: 2025-12-24 02:53:35.995147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff45682dcc2'
down_revision = 'c156be297dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('largura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comprimento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('comprimento')
        batch_op.drop_column('largura')
        batch_op.drop_column('altura')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
