"""cria produto_base e vinculo opcional em produto (fase 1)

Revision ID: 2801260801f8
Revises: a63e8e1c02af
Create Date: 2026-08-14 17:22:13.626993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2801260801f8'
down_revision = 'a63e8e1c02af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('comprimento', sa.Integer(), nullable=True),
    sa.Column('online_ativo', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_base_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_produto_produto_base_id', 'produto_base', ['produto_base_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produto_produto_base_id', type_='foreignkey')
        batch_op.drop_column('produto_base_id')

    op.drop_table('produto_base')
    # ### end Alembic commands ###
