"""adiciona url da etiqueta salva na venda

Revision ID: 29cb4dbde5c7
Revises: b3d002c28c02
Create Date: 2026-08-12 18:53:18.267832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cb4dbde5c7'
down_revision = 'b3d002c28c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiqueta_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('etiqueta_url')

    # ### end Alembic commands ###
