"""Adiciona campos de endereço e entrega gratis na Venda

Revision ID: 3a1b9c8d7e6f
Revises: fde2903279af
Create Date: 2025-09-26 18:30:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1b9c8d7e6f'
down_revision = 'fde2903279af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega_gratuita', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('entrega_rua', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('entrega_numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('entrega_bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entrega_cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entrega_cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('entrega_complemento', sa.String(length=100), nullable=True))

    # Preenche o valor padrão para registros existentes para evitar problemas com 'nullable=False'
    op.execute("UPDATE venda SET entrega_gratuita = FALSE WHERE entrega_gratuita IS NULL")

    # Altera a coluna para não permitir nulos após o preenchimento
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('entrega_gratuita', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('entrega_complemento')
        batch_op.drop_column('entrega_cep')
        batch_op.drop_column('entrega_cidade')
        batch_op.drop_column('entrega_bairro')
        batch_op.drop_column('entrega_numero')
        batch_op.drop_column('entrega_rua')
        batch_op.drop_column('entrega_gratuita')

    # ### end Alembic commands ###