"""add cor_hex to produto

Revision ID: 5e2a6a752c92
Revises: 46f8dc194626
Create Date: 2025-12-04 00:52:56.621869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2a6a752c92'
down_revision = '46f8dc194626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_hex', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('cor_hex')

    # ### end Alembic commands ###
