"""adiciona flag de revisao manual para pedidos de risco elevado

Revision ID: 68566889893b
Revises: a4c1f80c7531
Create Date: 2026-08-16 16:11:57.358241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68566889893b'
down_revision = 'a4c1f80c7531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revisao_manual_necessaria', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('revisao_manual_necessaria')

    # ### end Alembic commands ###
