"""add promocao fields to produto

Revision ID: 6a4f5fea26bf
Revises: 22d2d4fd64c4
Create Date: 2026-08-26 09:56:18.945761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4f5fea26bf'
down_revision = '22d2d4fd64c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_promocional', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('promocao_ativa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promocao_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('promocao_fim', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('promocao_fim')
        batch_op.drop_column('promocao_inicio')
        batch_op.drop_column('promocao_ativa')
        batch_op.drop_column('preco_promocional')

    # ### end Alembic commands ###
