"""add feedback compra

Revision ID: 77feec2a8e4d
Revises: 13b5a74768fe
Create Date: 2026-07-31 19:02:03.296441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77feec2a8e4d'
down_revision = '13b5a74768fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_venda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_compra')
    # ### end Alembic commands ###
