"""adiciona tabela promocao_automatica

Revision ID: 79ce930ef767
Revises: cfdddb34c06a
Create Date: 2026-08-02 21:06:27.096174

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta


# revision identifiers, used by Alembic.
revision = '79ce930ef767'
down_revision = 'cfdddb34c06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocao_automatica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('gatilho', sa.String(length=30), nullable=False),
    sa.Column('codigo_cupom', sa.String(length=50), nullable=True),
    sa.Column('prefixo_codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo_desconto', sa.String(length=20), nullable=False),
    sa.Column('valor_desconto', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Migração de dados: substitui o antigo par Configuracao + Cupom "PRIMEIRACOMPRA" ---
    bind = op.get_bind()
    agora = datetime.utcnow() - timedelta(hours=3)

    def ler_config(chave, padrao=None):
        row = bind.execute(sa.text("SELECT valor FROM configuracao WHERE chave = :chave"), {"chave": chave}).fetchone()
        return row[0] if row else padrao

    pc_ativo = str(ler_config('promo_primeira_compra_ativo', 'false')).lower() == 'true'
    pc_percent = float(ler_config('promo_primeira_compra_percent', 10) or 10)
    pa_ativo = str(ler_config('promo_primeira_avaliacao_ativo', 'false')).lower() == 'true'
    pa_percent = float(ler_config('promo_primeira_avaliacao_percent', 10) or 10)

    promocao_automatica = sa.table(
        'promocao_automatica',
        sa.column('nome', sa.String), sa.column('gatilho', sa.String),
        sa.column('codigo_cupom', sa.String), sa.column('prefixo_codigo', sa.String),
        sa.column('tipo_desconto', sa.String), sa.column('valor_desconto', sa.Float),
        sa.column('ativo', sa.Boolean), sa.column('data_criacao', sa.DateTime)
    )
    op.bulk_insert(promocao_automatica, [
        {
            'nome': 'Primeira Compra', 'gatilho': 'primeira_compra',
            'codigo_cupom': 'FITPRO10', 'prefixo_codigo': None,
            'tipo_desconto': 'percentual', 'valor_desconto': pc_percent,
            'ativo': pc_ativo, 'data_criacao': agora
        },
        {
            'nome': 'Primeira Avaliação', 'gatilho': 'primeira_avaliacao',
            'codigo_cupom': None, 'prefixo_codigo': 'REVIEW-',
            'tipo_desconto': 'percentual', 'valor_desconto': pa_percent,
            'ativo': pa_ativo, 'data_criacao': agora
        },
    ])

    # Remove o cupom "sombra" PRIMEIRACOMPRA (nunca foi vinculado a nenhuma venda: o checkout
    # sempre tratou essa promoção via um objeto virtual, não pelo registro real do Cupom)
    bind.execute(sa.text("DELETE FROM cupom WHERE codigo = 'PRIMEIRACOMPRA'"))
    bind.execute(sa.text(
        "DELETE FROM configuracao WHERE chave IN "
        "('promo_primeira_compra_ativo', 'promo_primeira_compra_percent', "
        "'promo_primeira_avaliacao_ativo', 'promo_primeira_avaliacao_percent')"
    ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocao_automatica')
    # ### end Alembic commands ###
