"""Add online fields

Revision ID: 7f9510988a71
Revises: 7617f6f7e84a
Create Date: 2025-11-25 13:26:19.751016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9510988a71'
down_revision = '7617f6f7e84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('endereco_rua', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('endereco_numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco_bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco_complemento', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_cliente_email', ['email'])

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online_ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), nullable=True))

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('id_vendedor',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('id_vendedor',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('destaque')
        batch_op.drop_column('descricao')
        batch_op.drop_column('online_ativo')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cliente_email', type_='unique')
        batch_op.drop_column('endereco_complemento')
        batch_op.drop_column('endereco_cep')
        batch_op.drop_column('endereco_cidade')
        batch_op.drop_column('endereco_bairro')
        batch_op.drop_column('endereco_numero')
        batch_op.drop_column('endereco_rua')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
