"""add transacao_id to pagamento

Revision ID: 7fd6cc3a7af5
Revises: 07e5812abfb7
Create Date: 2026-07-25 13:40:12.097436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd6cc3a7af5'
down_revision = '07e5812abfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transacao_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_column('transacao_id')

    # ### end Alembic commands ###
