"""add_troco_to_venda

Revision ID: 83ef9b2164a6
Revises: cc1c15dc0998
Create Date: 2025-12-01 07:51:00.326191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ef9b2164a6'
down_revision = 'cc1c15dc0998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('troco', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('troco')

    # ### end Alembic commands ###
