"""add ordem to produto_imagem

Revision ID: 8b41edffa799
Revises: 9f8e7d6c5b4a
Create Date: 2025-12-15 17:41:10.054002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b41edffa799'
down_revision = '9f8e7d6c5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_imagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_imagem', schema=None) as batch_op:
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###
