"""adiciona codigo_servico_frete em venda

Revision ID: 9f7a86223102
Revises: 513e833a1c0b
Create Date: 2026-08-01 13:45:31.850069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7a86223102'
down_revision = '513e833a1c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_servico_frete', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('codigo_servico_frete')

    # ### end Alembic commands ###
