"""adiciona token de redefinicao de senha em cliente

Revision ID: a4c1f80c7531
Revises: ca20587dacdc
Create Date: 2026-08-15 13:09:19.111429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c1f80c7531'
down_revision = 'ca20587dacdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_senha_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_senha_expira_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('reset_senha_expira_em')
        batch_op.drop_column('reset_senha_token_hash')

    # ### end Alembic commands ###
