"""adiciona melhor_envio_id em venda

Revision ID: a63e8e1c02af
Revises: 29cb4dbde5c7
Create Date: 2026-08-14 14:51:03.189743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63e8e1c02af'
down_revision = '29cb4dbde5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('melhor_envio_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('melhor_envio_id')

    # ### end Alembic commands ###
