"""add_deletado_to_produto

Revision ID: ab25ac52ce91
Revises: 7fd6cc3a7af5
Create Date: 2026-07-27 19:38:24.118568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab25ac52ce91'
down_revision = '7fd6cc3a7af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('deletado')

    # ### end Alembic commands ###
