"""adiciona flag de lembrete de carrinho abandonado

Revision ID: b3d002c28c02
Revises: d433f48a8944
Create Date: 2026-08-12 18:07:47.085938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d002c28c02'
down_revision = 'd433f48a8944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        # server_default garante que as vendas ja existentes recebam False (nao teriam
        # como receber lembrete de qualquer forma - o job so olha pra Pendente recentes).
        batch_op.add_column(sa.Column('lembrete_abandono_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('lembrete_abandono_enviado', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('lembrete_abandono_enviado')

    # ### end Alembic commands ###
