"""adiciona data de nascimento e recompensa de aniversario em cliente

Revision ID: bc4599f335c8
Revises: 2801260801f8
Create Date: 2026-08-14 21:53:45.822749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4599f335c8'
down_revision = '2801260801f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('desconto_aniversario_percentual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desconto_aniversario_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('desconto_aniversario_expira_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aniversario_ultimo_ano_notificado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('aniversario_ultimo_ano_notificado')
        batch_op.drop_column('desconto_aniversario_expira_em')
        batch_op.drop_column('desconto_aniversario_tipo')
        batch_op.drop_column('desconto_aniversario_percentual')
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
