"""adiciona recompensa automatica de primeira avaliacao em Cliente

Revision ID: c0566a844e2f
Revises: eedd2cb88418
Create Date: 2026-08-03 16:27:26.713826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0566a844e2f'
down_revision = 'eedd2cb88418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recompensa_avaliacao_concedida', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('desconto_avaliacao_percentual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desconto_avaliacao_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('desconto_avaliacao_expira_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('desconto_avaliacao_expira_em')
        batch_op.drop_column('desconto_avaliacao_tipo')
        batch_op.drop_column('desconto_avaliacao_percentual')
        batch_op.drop_column('recompensa_avaliacao_concedida')

    # ### end Alembic commands ###
