"""add tipo_entrega to venda

Revision ID: c156be297dc4
Revises: 01304a9b5081
Create Date: 2025-12-23 00:47:23.227932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c156be297dc4'
down_revision = '01304a9b5081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_entrega', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('tipo_entrega')

    # ### end Alembic commands ###
