"""cria tabela de medidas por categoria

Revision ID: c5957d7fd5c2
Revises: 68566889893b
Create Date: 2026-08-18 08:22:27.275299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5957d7fd5c2'
down_revision = '68566889893b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('colunas', sa.JSON(), nullable=False),
    sa.Column('linhas', sa.JSON(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_medidas')
    # ### end Alembic commands ###
