"""Adiciona relacao M-M para Venda-Cupom e atualiza campos de desconto

Revision ID: c8327e90a6d3
Revises: e9c1b2a3f4d5
Create Date: 2025-10-17 10:06:24.781057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8327e90a6d3'
down_revision = 'e9c1b2a3f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda_cupons',
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('venda_id', 'cupom_id'),
    info={'bind_key': None}
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto_total', sa.Float(), nullable=True))
        batch_op.drop_column('cupom_utilizado')
        batch_op.drop_column('valor_desconto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_desconto', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cupom_utilizado', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('desconto_total')

    op.drop_table('venda_cupons')
    # ### end Alembic commands ###
