"""adiciona status_detail_mp em venda

Revision ID: ca20587dacdc
Revises: bc4599f335c8
Create Date: 2026-08-14 22:19:45.210344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca20587dacdc'
down_revision = 'bc4599f335c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_detail_mp', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('status_detail_mp')

    # ### end Alembic commands ###
