"""adiciona versao_termos e user_agent_comprador em venda

Revision ID: cfdddb34c06a
Revises: 9f7a86223102
Create Date: 2026-08-01 18:51:08.640338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdddb34c06a'
down_revision = '9f7a86223102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versao_termos', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_agent_comprador', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('user_agent_comprador')
        batch_op.drop_column('versao_termos')

    # ### end Alembic commands ###
