"""adiciona tabela de eventos de marketing (pixel/capi)

Revision ID: d433f48a8944
Revises: f4c47837879e
Create Date: 2026-08-12 16:08:14.769645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd433f48a8944'
down_revision = 'f4c47837879e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_marketing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('id_venda', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.String(length=255), nullable=True),
    sa.Column('enviado_meta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_marketing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_marketing_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_marketing_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_marketing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_marketing_tipo'))
        batch_op.drop_index(batch_op.f('ix_evento_marketing_timestamp'))

    op.drop_table('evento_marketing')
    # ### end Alembic commands ###
