"""add hist cost to itemvenda

Revision ID: e155679ec2eb
Revises: 8b41edffa799
Create Date: 2025-12-21 00:53:30.405701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e155679ec2eb'
down_revision = '8b41edffa799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_custo_momento', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venda', schema=None) as batch_op:
        batch_op.drop_column('preco_custo_momento')

    # ### end Alembic commands ###
