"""adiciona marcos de data e motivo de cancelamento em Venda

Revision ID: eedd2cb88418
Revises: 79ce930ef767
Create Date: 2026-08-03 12:30:53.464048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedd2cb88418'
down_revision = '79ce930ef767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_cancelamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('motivo_cancelamento')
        batch_op.drop_column('data_cancelamento')
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('data_envio')
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###
