"""adiciona tabela de contagem de visitas da loja online

Revision ID: f4c47837879e
Revises: c0566a844e2f
Create Date: 2026-08-04 12:04:58.644047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c47837879e'
down_revision = 'c0566a844e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('pagina', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visita_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visita_site_ip_hash'), ['ip_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visita_site_ip_hash'))

    op.drop_table('visita_site')
    # ### end Alembic commands ###
