"""Adiciona funcionalidade de cupons por produto

Revision ID: fde2903279af
Revises: 
Create Date: 2025-09-20 14:11:48.459801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde2903279af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupom', schema=None) as batch_op:
        # ADICIONE O server_default='total' AQUI:
        batch_op.add_column(sa.Column('aplicacao', sa.String(length=20), nullable=False, server_default='total'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupom', schema=None) as batch_op:
        batch_op.drop_column('aplicacao')

    # ### end Alembic commands ###
